### ISSUE TITLE
None of the punishments works.

### ISSUE THREAD

**Issue by nobodySophie** [soumaxetuirk/PD-AntiCheat#10]
So i tried out every possible punishment except lowering their level to 1 and none of them worked. Im not sure if its just me or if its an actual issue honestly.

[as u can see it detects them properly and marks them but doesnt do anything else](https://prnt.sc/u2dqsy)

**Comment by soumaxetuirk** [comment]
Was it a private lobby ? In private lobby , punishment is disabled.
Otherwise if you are still having the issue then try to reinstall the mod. also try to delete the save file present in mods/saves/PDASetting.txt

**Comment by nobodySophie** [comment]
it was a public lobby, i tried reinstalling it and after i removed safe file and joined some cheater's game it still detected him and all but didnt do anything and after a minute i got crash. Not sure if it was caused by mod or the game itself

```
Application has crashed: access violation

Current thread: Main
Script stack:
          _create_carry_unit()  lib/units/beings/player/huskplayermovement.lua:377  
            set_visual_carry()  lib/units/beings/player/huskplayermovement.lua:349  
            set_synced_carry()  lib/managers/playermanager.lua:2947                 
                                lib/network/handlers/unitnetworkhandler.lua:2423  
```

**Comment by nobodySophie** [comment]
Alright i figured it out. I have a mod called lobby settings and for some reason when i some day created a private lobby it somehow managed to stay as private even tho i was joining other lobbies (or at least made PD anticheat treat it as private). I just simply created new contract and changed permission to public, now everything works. My bad, sorry
