### ISSUE TITLE
Downgrade to lvl 1 option is gone and i think auto update doesn't work.

### ISSUE THREAD

**Issue by nobodySophie** [soumaxetuirk/PD-AntiCheat#12]
https://prnt.sc/u4xvxd

about auto update: i have 3.3 version and it says that its up to date, dont see any newer version
edit: nvm u didnt post 3.4 version yet only patch notes mb.

**Comment by soumaxetuirk** [comment]
Update 3.4 delayed due to few last minute changes. It is a minor update for cheater's  not getting punishment in few cases.
Downgrade option is removed from release 3.3 . I am trying to optimised the mod as much as possible for now, new things will be added in release 4.0
