### ISSUE TITLE
Is it possible to add manually a mod into the list?

### ISSUE THREAD

**Issue by EfremovSerg** [soumaxetuirk/PD-AntiCheat#14]
I wonder if this is a possibility. I tried to add to the function "Modtest2" but it seems like I have no effect. Any clues?

**Comment by soumaxetuirk** [comment]
Yes! You can.
Note : add the names with **small letters** only.

If it's not working then share the modtest2 function codes.

**Comment by EfremovSerg** [comment]
Well, I did some tests. Sometimes it didn't trigger on Silent Assasin, but I've seen 2 out of 4 times someone had this mod and getting electrocuted.

Since the Github have issue formatting this piece of code, I'll send a screenshot of this exact fragment of code
![PD_ANTICHEAT](https://user-images.githubusercontent.com/60647610/93684128-eb306d00-fab7-11ea-9e76-d9116bcb021d.PNG)

**Comment by soumaxetuirk** [comment]
Custom list option is now supported from 3.6 
no need to edit the mod files any more. edit text file present at  "Payday_game_directory/mods/saves/PDA_flaggedmods.txt".
Custom list will not be affected with mod updates.
