### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ihatelua** [soumaxetuirk/PD-AntiCheat#15]
The mod is not working.
Is this mod not working now?

**Comment by ihatelua** [comment]
It's working. I think there was a mistake.

**Comment by nobodySophie** [comment]
I think he kind of abandoned this project

**Comment by nobodySophie** [comment]
tho I think it should work flawlessly

**Comment by ihatelua** [comment]
Is there a reason for the abandonment?

**Comment by soumaxetuirk** [comment]
> It's working. I think there was a mistake.

Please report if you find any kind of mistake or error. I will be happy to help.
Not abandoned,I got busy. last release 3.52 should be working perfectly with recent updates of game.
