### ISSUE TITLE
Countdown to crash doesnt work

### ISSUE THREAD

**Issue by nobodySophie** [soumaxetuirk/PD-AntiCheat#17]
Hello, its been awhile since i played pd2 but today i noticed that this function isnt crashing people anymore just gets them downed and after u "revive" them they are stuck in this position on my screen but they can move freely etc. just like nothing happened. I know that u released final version and finished working on this project but thought that maybe u could try to fix this issue. 
Thanks in advance

**Comment by soumaxetuirk** [comment]
Probably happened due to network lag or something. I tested myself with recent update 200, Its working like it used to.
SO if you seeing this error multiple times then let me know..
