### ISSUE TITLE
#17

### ISSUE THREAD

**Issue by nobodySophie** [soumaxetuirk/PD-AntiCheat#18]
#17 
![Screenshot_33](https://user-images.githubusercontent.com/69479853/99198405-b4659300-2798-11eb-87c1-287525bce907.jpg)

edit: sorry i should've just reopened previous discussion

**Comment by nobodySophie** [comment]
and sorry i should've just reopened previous discussion

**Comment by nobodySophie** [comment]
another thing i noticed is that they dont even get downed on their site 
![Screenshot_34](https://user-images.githubusercontent.com/69479853/99198720-c0525480-279a-11eb-90b6-91dcb26f60cb.jpg)

**Comment by soumaxetuirk** [comment]
I checked a couple of times and finally found it ! So its not your game.

"countdown to crash" is now updated and It will crash as soon as a cheater is found. (version 4.0.1)
Other punishments will also be fixed very soon.

**Comment by nobodySophie** [comment]
ah, thanks
