### ISSUE TITLE
Better update system idea

### ISSUE THREAD

**Issue by SnakePin** [soumaxetuirk/PD-AntiCheat#3]
I'd suggest setting the `download_url` in the `meta.json` file to https://github.com/soumaxetuirk/PD-AntiCheat/archive/master.zip ,moving the contents of the `PD AntiCheat` folder to the root and moving `meta.json` to a different branch in order to avoid having to update the zip file. This is exactly what WolfHUD does.

**Comment by soumaxetuirk** [comment]
Thank you.
This will be organised
