### ISSUE TITLE
Cheater didn't get detected upon joining my game.

### ISSUE THREAD

**Issue by nobodySophie** [soumaxetuirk/PD-AntiCheat#5]
**Hi, some cheater joined my game with a P3DHack tag but he didnt have cheater mark on his head (seems like he didnt use any dlc weapons etc.). Not sure if its an issue but i thought it was detecting cheating mods, correct me if im wrong tho.**

https://prnt.sc/tynlwr - had to kick him manually

**Comment by soumaxetuirk** [comment]
He must had kept his mod list hidden, that way PD-Anticheat could not find his mod list. 

As 99% cheaters don't buy P3Dhack, I will mark all username with " [P3DHack]" as the cheaters.

**Comment by nobodySophie** [comment]
Oh, yes i totally forgot about that. and thanks, that would be awesome!

**Comment by soumaxetuirk** [comment]
This has been implemented in latest update (2.42) .
