### ISSUE TITLE
Announce option is resetting itself.

### ISSUE THREAD

**Issue by nobodySophie** [soumaxetuirk/PD-AntiCheat#7]
Hi, so i noticed that each time i change announce option it resets itself to default "everyone" after every heist or game restart.

**Comment by nobodySophie** [comment]
also i wanted to ask if u ever thought about adding option to give slow-mo to cheater, like stopthecheater does but its outdated and discontiuned and have a few issues.

**Comment by soumaxetuirk** [comment]
It only doesn't show last saved in menu after restart. But the mod uses the last setting you saved correctly.
Its a  minor mistake I haven't looked yet, It will be fixed by next release.

**Comment by soumaxetuirk** [comment]
> also i wanted to ask if u ever thought about adding option to give slow-mo to cheater, like stopthecheater does but its outdated and discontinued and have a few issues.

Slow-mo will not be added as there are already anti-slow motion  mods to counter it. Also I do not intend to go to the original author for permission...
Few already in progress are: direct custody, teleport to a locked container(closed place) if available in map(else to starting point)

**Comment by soumaxetuirk** [comment]
Announce setting issue resolved in update 2.51
