### ISSUE TITLE
Crash in lobby

### ISSUE THREAD

**Issue by nobodySophie** [soumaxetuirk/PD-AntiCheat#8]
### Hi, i joined the game to try out new punishments (i chose the "countdown to crash") and unfortunately as soon as i joined they managed to finish this heist so i got card pickup screen then we moved to lobby and after like 5s my game crashed.

```
Application has crashed: C++ exception
mods/PD AntiCheat/mod/mod.lua:276: attempt to index field 'hud' (a nil value)

SCRIPT STACK

punishment() @mods/PD AntiCheat/mod/mod.lua:256
func() @mods/PD AntiCheat/mod/mod.lua:95
mark_cheater() @mods/base/req/core/Hooks.lua:268
verify_job() lib/network/base/networkpeer.lua:215
lib/network/base/handlers/connectionnetworkhandler.lua:337
```

**Comment by nobodySophie** [comment]
Now it crashed upon joining the same lobby, i think "the fixes" mod may caused this one 

> original() @mods/The Fixes/clientnetworksession.lua:6

```
Application has crashed: C++ exception
mods/PD AntiCheat/mod/mod.lua:276: attempt to index field 'hud' (a nil value)

SCRIPT STACK

punishment() @mods/PD AntiCheat/mod/mod.lua:256
func() @mods/PD AntiCheat/mod/mod.lua:95
mark_cheater() @mods/base/req/core/Hooks.lua:268
verify_job() lib/network/base/networkpeer.lua:215
join_req_reply_orig() lib/network/base/clientnetworksession.lua:140
original() @mods/The Fixes/clientnetworksession.lua:6
on_join_request_reply() @mods/base/req/core/Hooks.lua:188
lib/network/base/handlers/connectionnetworkhandler.lua:60
```

**Comment by nobodySophie** [comment]
I got the same crash after i change the punishment to electrocuted, but now whenever i try to join this particular lobby it always fails to join.

**Comment by soumaxetuirk** [comment]
Recent payday 2 update and the later released minor fix  may caused such crash. PD-Anticheat only works in heist, it should be stayed inactive in a lobby. This code was present in previous versions of this mods too.

So kindly confirm that you and the host are in same game version(or else you will not able to join same lobby). Please update your mod to 3.01 ,it should fix the crash issue. Let me know otherwise again.

**Comment by nobodySophie** [comment]
It seems to work now. I couldn't confirm or know what their game version was as it was some random cheating i just could reconnect to their lobby multiple times tho. Also i noticed that u asked for help with translation well i could help with translation to polish but i have never done that before so i dno what u would expect me to do

**Comment by soumaxetuirk** [comment]
I am willing to update the mods for all supported language and also mod based languages too.
Right side of each line needs to be replaced with polish line. for settings and chat messages.

[File link](https://github.com/soumaxetuirk/PD-AntiCheat/blob/master/PD%20AntiCheat/menu/local.txt)

**Comment by nobodySophie** [comment]
Alright.
