### ISSUE TITLE
Countdown to crash (most likely) doesn't work.

### ISSUE THREAD

**Issue by nobodySophie** [soumaxetuirk/PD-AntiCheat#9]
Hi, i think this punishment doesnt work cause the cheater got detected and marked as one tho they didn't crash or anything, other punishments seem to working without any problems. Correct me if im wrong and this punishment was supposed to do something different of course

**Comment by soumaxetuirk** [comment]
It was meant do something but during my tests it crashed cheaters' games.So I just left it that way....
Once they detected, they will get downed and a 30 sec times will start for their revive. trying to revive them or at the end of the revive timer his game will crash.

Again It was meant for something else but it did not work so i left it like that.....

**Comment by nobodySophie** [comment]
Oh, i get u. Thanks for explaining
